### ISSUE TITLE
存在しないユーザにメールが送れる

### ISSUE THREAD

**Issue by okirakumine** [testusuke/Man10Mail#1]
MailCommand.kt
```
                val id = args[1]
                val targetPlayer = Bukkit.getOfflinePlayer(id)
                val uuid = targetPlayer.uniqueId.toString()
                if (uuid.isEmpty()) {
                    sender.sendMessage("${prefix}§cプレイヤー情報を取得できませんでした。could not get player info.")
                    return false
                }
```
ここでargs[1]がプレイヤー存在するかチェックしているようですが
実際にはプレイヤーが存在していなくてもメールは送れてしまいます。
targetPlayer.uniqueId.toString() が返す値の問題？

**Comment by testusuke** [comment]
Thanks for report!
Yes. Can send mail to not-exist player is the fact.
That program has wrong. I will write truly again.
Thank you very much. I do my best!
