### ISSUE TITLE
所持金がメール送信に必要な額とピッタリ同じだと送信できない

### ISSUE THREAD

**Issue by okirakumine** [testusuke/Man10Mail#7]
src/main/kotlin/net/testusuke/open/man10mail/MailCommand.kt 
86行目
```
if(!sender.hasPermission(Permission.ADMIN) && money < plugin.MONEY_SEND_MAIL.toDouble()){
```
は
```
if(!sender.hasPermission(Permission.ADMIN) && money <= plugin.MONEY_SEND_MAIL.toDouble()){
```
にすべきかと。

**Comment by testusuke** [comment]
変数moneyは所持金
定数plugin.MONEY_SEND_MAILは必要料金
`if(!sender.hasPermission(Permission.ADMIN) && money < plugin.MONEY_SEND_MAIL.toDouble()){`
所持金と必要料金を比較して必要料金の方が大きい場合、所持金が足りないということで実行を中断します。
もし、
`if(!sender.hasPermission(Permission.ADMIN) && money <= plugin.MONEY_SEND_MAIL.toDouble()){`
にしてしまうと、所持金と必要料金を比較して必要料金と同じ場合、必要料金の方が大きい場合に実行してしまいます。
そのように変更してしまうと、必要料金とぴったり同じだと送信できなくなってしまいます。

誤解を与えてしまうのは、自分のソースコードの書き方があまり良くないのだと思います。誤解をまねかないようなソースコードを書くように努力しますね。
ご報告ありがとうございます。
